"""add_connections

Revision ID: 5b6272723c3a
Revises: 4606ead5e323
Create Date: 2025-05-05 00:02:35.660890

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b6272723c3a"
down_revision: Union[str, None] = "4606ead5e323"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "device", sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("device", "type")
    # ### end Alembic commands ###
